### ISSUE TITLE
Python 3.6 is End of Life

### ISSUE THREAD

**Issue by zeke** [arXiv/arxiv-browse#256]
This project is currently configured to use Python v3.6, an old version which reached [End of Life in December 2021](https://endoflife.date/python) and no longer receives security updates.

https://github.com/arXiv/arxiv-browse/blob/ff097e24b85a7e03207ccc03565da42e587b12cf/Pipfile#L52-L53

In the interest of application security, it would be wise to upgrade to a newer, supported version of Python.

**Comment by nichtich** [comment]
I failed to get the application running with current Python or pyenv, other had similar trouble (#185). Looks like it is legacy code with limited maintanability and security until one of the current main developers (@cbf66, @bmaltzan, @bdc34?) has resources for cleanup. There was [an attempt](https://github.com/arXiv/arxiv-browse/pull/282) to update the project to Python 3.10 so it just seems to be a matter of priorities.

**Comment by cbf66** [comment]
@nichtich -- you're looking at the wrong branch for Python 3.10. See [https://github.com/arXiv/arxiv-browse/tree/gcp-cd-arxiv-development](https://github.com/arXiv/arxiv-browse/tree/gcp-cd-arxiv-development) which is running in beta test at [https://browse.arxiv.org/](https://browse.arxiv.org/).

That's the path forward. We're probably not going to upgrade the legacy system from Python 3.6 because it gets tied up in dependency knots. But that won't be running for much longer.

**Comment by bdc34** [comment]
Fixed.

**Comment by zeke** [comment]
Thanks, @bdc34 👍🏼
